### ISSUE TITLE
Requests for Enhancements: support Cloudflare AI translator API?

### ISSUE THREAD

**Issue by ktownag** [ychoi-kr/omegat-plugin-deepl-api-free#1]
THANKS

**Comment by ychoi-kr** [comment]
Thank you for your suggestion regarding the support for the Cloudflare AI translator API.

At this time, I do not have plans to support the Cloudflare AI translator API. 
However, since this project is open source, you or someone else is welcome to fork the repository and add support for the Cloudflare AI translator API.
